import selenium
import time
from pwinput import pwinput
from selenium import webdriver
import os, sys
print("|===================tool=report=facebook===================|")
print("|                                                          |")
print("|                        tool by huy                       |")
print("|                                                          |")
print("|                        do not reup                       |")
print("|                                                          |")
print("|                     vui lòng nhập key                    |")
print("|                                                          |")
print("|                                          edit: huy hoàng |")
print("|==========================================================|")
time.sleep(1)
you=input("nhập key: ")
if you == "1134231":
	print("key đúng vui lòng đợi...")
	time.sleep(3)
	logo=("<------------------------------------------------------------->")
	print(logo)
	user=input("link facebook:")
	tk=input("nhập tk facebook của bạn: ")
	mk=pwinput("nhập mk facebook của bạn: ","*")
	tk=str(tk)
	mk=str(mk )
	with open("hack.txt","a") as file:
		print("tài khoản: ")
		file.write(f"{tk} \n")
		print("mật khẩu: ")
		file.write(mk)
	driver = webdriver.Chrome()
	driver.get(user)
	driver.execute_script('document.querySelector(".om3e55n1.g4tp4svg.alzwoclg.jez8cy9q.jcxyg2ei.i85zmo3j.sr926ui1.jl2a5g8c.k7n6ui8p.b41d885q.hmqrhxox.got7tec9.frfouenu.bonavkto.djs4p424.r7bn319e.bdao358l.a5wdgl2o.ed17d2qt.r227ecj6.gt60zsk1").click()')
	time.sleep(1)
	driver.find_element_by_xpath('/html/body/div[1]/div/div[1]/div/div[4]/div/div/div[1]/div/div[2]/div/div/div/div[2]/div/div/form/div/div[3]/div/label/div/div/input').send_keys(tk)
	time.sleep(1)
	driver.find_element_by_xpath('/html/body/div[1]/div/div[1]/div/div[4]/div/div/div[1]/div/div[2]/div/div/div/div[2]/div/div/form/div/div[4]/div/label/div/div/input').send_keys(mk)
	time.sleep(1)
	driver.find_element_by_xpath('/html/body/div[1]/div/div[1]/div/div[4]/div/div/div[1]/div/div[2]/div/div/div/div[2]/div/div/form/div/div[5]/div/div').click()
	time.sleep(2)
	driver.execute_script('document.querySelector(".om3e55n1.g4tp4svg.alzwoclg.jez8cy9q.jcxyg2ei.i85zmo3j.sr926ui1.jl2a5g8c.k7n6ui8p.b41d885q.hmqrhxox.got7tec9.frfouenu.bonavkto.djs4p424.r7bn319e.bdao358l.a5wdgl2o.ed17d2qt.r227ecj6.gt60zsk1").click()')
	time.sleep(2)
	driver.find_element_by_xpath("/html/body/div[1]/div[1]/div[1]/div/div[3]/div/div/div/div[2]/div/div/div[1]/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[4]").click()
	time.sleep(2)
	driver.find_element_by_xpath("/html/body/div[1]/div[1]/div[1]/div/div[4]/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div[3]/div/div[2]/div/div/div[2]/div/div/div/div[1]").click()
	time.sleep(2)
	driver.find_element_by_xpath('//*[@id="mount_0_0_7K"]/div[1]/div[1]/div/div[4]/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div[4]/div/div/div[4]/div/div').click()
	time.sleep(2)
	driver.find_element_by_xpath('/html/body/div[1]/div[1]/div[1]/div/div[4]/div/div/div[2]/div/div/div[1]/div/div[2]/div/div/div/div[4]/div[2]/div/div/div/div').click()
else:
	print("sai key")